#Keycloak/OAuth properties
security:
  oauth2:
    resource:
      jwt:
        key-value: ${KEYCLOAK_PUBLIC_KEY}

#DB Properties
spring:
  jmx:
    enabled: false
  datasource:
    hikari:
      pool-name: course-api-cp
      maximum-pool-size: ${MAXIMUM_POOL_SIZE}
      connection-timeout: ${CONNECTION_TIMEOUT}
      max-lifetime: ${MAX_LIFETIME}
    url: ${JDBC_URL}
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false

#Logging properties
logging:
  file:
    max-history: 1
    clean-history-on-start: true
    max-size: 20MB
    name: /logs/app.log
  #pattern:
  #  file: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  #  console: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  level:
    ca:
      bc:
        gov:
          educ:
            api:
              course: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}

#Local properties
server:
  undertow:
    threads:
      worker: 128
      io: 16
  #port: ${HTTP_PORT}

#API Documentation
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs-ui.html
    operationsSorter: alpha

#Ebdpoints
endpoint:
  grad-program-api:
    rule-detail:
      url : https://educ-grad-program-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/program/programrules/%s