#DB Properties
spring:
  jmx:
    enabled: false
  datasource:
    hikari:
      pool-name: educ-grad-course-api-cp
      maximum-pool-size: ${MAXIMUM_POOL_SIZE}
      connection-timeout: ${CONNECTION_TIMEOUT}
      max-lifetime: ${MAX_LIFETIME}
    url: ${CONNECTION_STRING}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  flyway:
    enabled: ${ENABLE_FLYWAY}
    baseline-on-migrate: false
    table: FLYWAY_SCHEMA_HISTORY
    url: ${CONNECTION_STRING}
    schema: ${USERNAME}
    user: ${USERNAME}
    password: ${PASSWORD}
    location: classpath:db/migration
  #Keycloak/OAuth properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URL}
          jwk-set-uri: ${TOKEN_ISSUER_URL}/protocol/openid-connect/certs

#Logging properties
logging:
  file:
    name: /logs/app.log
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 20MB
      clean-history-on-start: true
  pattern:
    #  file: "%d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n"
    #  console: "%d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n"
    file: '{"time_stamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%3p" ,"thread":"%t" ,"class":"%logger{36}","msg":"%replace(%msg){"[\n\r\"]",""}", "exception":"%replace(%rEx{10}){"[\n\r\"]",""}","http_event":%X{httpEvent:-""},"message_event":%X{messageEvent:-""}}%nopex%n'
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%5p] [%t] [%logger{36}] [%replace(%msg){'[\n\r\"]',''} %X{httpEvent} %X{messageEvent}] %replace(%rEx{10}){'[\n\r\"]',''}%nopex%n"
  level:
    ca:
      bc:
        gov:
          educ:
            api:
              course: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}
    com:
      zaxxer:
        hikari: ERROR

#Resilience
resilience4j.retry:
  instances:
    generalgetcall:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 5s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    searchcoursecall:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 7s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    generalpostcall:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 5s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException

#Local properties
server:
  undertow:
    threads:
      worker: 128
      io: 16
  #port: ${HTTP_PORT}

#API Documentation
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs-ui.html
    operationsSorter: alpha

#Ebdpoints
endpoint:
  grad-program-api:
    rule-detail:
      url : ${GRAD_PROGRAM_API}api/v1/program/programrules/%s

#Splunk LogHelper
splunk:
  log-helper:
    enabled: ${ENABLE_SPLUNK_LOG_HELPER}
